eureka:
  client:
    serviceUrl:
      defaultZone: http://caihaixin:123456@eureka-server1:8761/eureka/,http://caihaixin:123456@eureka-server2:8762/eureka/,http://caihaixin:123456@eureka-server3:8763/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    preferIpAddress: true
server:
  port: 8081
spring:
  application:
    name: eureka-client-user-service
